import type { Registry } from "../../../../schema";

export const ui: Registry = [
  {
    name: "button",
    type: "registry:ui",
    description: "可点击的按钮组件，支持多种变体和状态",
    files: [{ path: "ui/button.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "input",
    type: "registry:ui",
    description: "文本输入框组件",
    files: [{ path: "ui/input.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "textarea",
    type: "registry:ui",
    description: "多行文本输入框组件",
    files: [{ path: "ui/textarea.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "checkbox",
    type: "registry:ui",
    description: "复选框组件",
    files: [{ path: "ui/checkbox.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "radio",
    type: "registry:ui",
    description: "单选框组件",
    files: [{ path: "ui/radio.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "switch",
    type: "registry:ui",
    description: "开关组件",
    files: [{ path: "ui/switch.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "select",
    type: "registry:ui",
    description: "下拉选择组件",
    files: [{ path: "ui/select.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "slider",
    type: "registry:ui",
    description: "滑块组件",
    files: [{ path: "ui/slider.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "avatar",
    type: "registry:ui",
    description: "头像组件，支持图片和文字",
    files: [{ path: "ui/avatar.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "badge",
    type: "registry:ui",
    description: "徽章组件",
    files: [{ path: "ui/badge.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "card",
    type: "registry:ui",
    description: "卡片容器组件",
    files: [{ path: "ui/card.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "skeleton",
    type: "registry:ui",
    description: "骨架屏加载占位组件",
    files: [{ path: "ui/skeleton.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "divider",
    type: "registry:ui",
    description: "分割线组件",
    files: [{ path: "ui/divider.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "tabs",
    type: "registry:ui",
    description: "标签页组件",
    files: [{ path: "ui/tabs.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "modal",
    type: "registry:ui",
    description: "模态框组件",
    files: [{ path: "ui/modal.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "dialog",
    type: "registry:ui",
    description: "对话框组件，带标题和操作按钮",
    files: [{ path: "ui/dialog.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "action-sheet",
    type: "registry:ui",
    description: "操作菜单组件",
    files: [{ path: "ui/action-sheet.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "alert",
    type: "registry:ui",
    description: "警告提示组件",
    files: [{ path: "ui/alert.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "toast",
    type: "registry:ui",
    description: "消息提示组件",
    files: [{ path: "ui/toast.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
  {
    name: "loading",
    type: "registry:ui",
    description: "加载指示器组件",
    files: [{ path: "ui/loading.tsx", type: "registry:ui" }],
    dependencies: [],
    registryDependencies: [],
  },
];
